language: objective-c
osx_image: xcode11.1
xcode_project: SFSymbol.xcodeproj # path to your xcodeproj folder
xcode_scheme: SFSymbols

env:
  - CODECOV_TOKEN="95b27dae-2aa2-4565-a2b4-2c73428c18e0"
script:
  - xcodebuild test -scheme SFSymbol -sdk iphonesimulator  -destination 'OS=13.1,name=iPhone 11' 
after_success:
  - bash <(curl -s https://codecov.io/bash)
