//
//  Multicolor.swift
//  SFSymbol
//
//  Created by Aaryan Kothari on 25/07/20.
//

import Foundation

@available(iOS 14.0, *)
public extension SFSymbol {
    var isMulticolor: Bool {
        switch self {
        case .alarm ,
             .arrowshapeTurnUpLeftCircleFill ,
             .arrowshapeTurnUpRightCircleFill ,
             .atBadgeMinus ,
             .atBadgePlus ,
             .badgePlusRadiowavesRight ,
             .bagBadgeMinus ,
             .bagBadgePlus ,
             .bellCircleFill ,
             .bookmarkFill ,
             .calendarBadgeMinus ,
             .calendarBadgePlus ,
             .calendarCircleFill ,
             .cartBadgeMinus ,
             .cartBadgePlus ,
             .checkmarkCircleFill ,
             .cloudBoltFill ,
             .cloudBoltRainFill ,
             .cloudDrizzleFill ,
             .cloudFill ,
             .cloudFogFill ,
             .cloudHailFill ,
             .cloudHeavyrainFill ,
             .cloudMoonBoltFill ,
             .cloudMoonFill ,
             .cloudMoonRainFill ,
             .cloudRainFill ,
             .cloudSleetFill ,
             .cloudSnowFill ,
             .cloudSunBoltFill ,
             .cloudSunFill ,
             .cloudSunRainFill ,
             .dropTriangleFill ,
             .envelopeCircleFill ,
             .exclamationmarkTriangleFill ,
             .flagCircleFill ,
             .flagFill ,
             .folderBadgeMinus ,
             .folderBadgePlus ,
             .folderCircleFill ,
             .gaugeBadgeMinus ,
             .gaugeBadgePlus ,
             .giftFill ,
             .gift ,
             .hurricane ,
             .infoCircleFill ,
             .linkCircleFill ,
             .locationCircleFill ,
             .memoriesBadgeMinus ,
             .memoriesBadgePlus ,
             .messageCircleFill ,
             .minusCircleFill ,
             .moonCircleFill ,
             .moonFill ,
             .moonStarsFill ,
             .pencilTipCropCircleBadgeMinus ,
             .pencilTipCropCircleBadgePlus ,
             .personBadgeMinus ,
             .personBadgePlus ,
             .personCropCircleBadgeCheckmark ,
             .personCropCircleBadgeMinus ,
             .personCropCircleBadgePlus ,
             .personCropCircleBadgeXmark ,
             .phoneBadgePlus ,
             .phoneCircleFill ,
             .phoneDownCircleFill ,
             .plusCircleFill ,
             .rectangleBadgeCheckmark ,
             .rectangleBadgeXmark ,
             .rectangleStackBadgeMinus ,
             .rectangleStackBadgePlus ,
             .smokeFill ,
             .snow ,
             .sparkles ,
             .starCircleFill ,
             .starFill ,
             .sunDustFill ,
             .sunHazeFill ,
             .sunMaxFill ,
             .sunriseFill ,
             .sunsetFill ,
             .textBadgeCheckmark ,
             .textBadgeMinus ,
             .textBadgePlus ,
             .textBadgeXmark ,
             .thermometerSnowflake ,
             .thermometer ,
             .timer ,
             .tornado ,
             .trashCircleFill ,
             .tropicalstorm ,
             .videoBadgePlus ,
             .videoCircleFill ,
             .waveformPathBadgeMinus ,
             .waveformPathBadgePlus ,
             .windSnow ,
             .wind ,
             .xmarkOctagonFill:
            return true

        default:
            return false
        }
    }
}
