name: Xcode build smoke test
run-name: Build smoke test by ${{ github.actor }}
on:
  pull_request:
    branches: [ "main" ]
jobs:
  smoke_test_build:
    name: Smoke Test (Build only)
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.app 
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild -scheme SFSymbol -target SFSymbol
      - name: Test
        run: xcodebuild test -scheme SFSymbol -target SFSymbolTests
